# Generated by Django 5.1.1 on 2024-10-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myform", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentmodel",
            name="address",
            field=models.CharField(default="Unknown Address", max_length=100),
        ),
        migrations.AddField(
            model_name="studentmodel",
            name="dob",
            field=models.DateField(default="2000-01-01"),
        ),
        migrations.AddField(
            model_name="studentmodel",
            name="email",
            field=models.EmailField(default="jhdsh@gmail.com", max_length=254),
        ),
        migrations.AddField(
            model_name="studentmodel",
            name="father_name",
            field=models.CharField(default="jhgdj", max_length=30),
        ),
        migrations.AddField(
            model_name="studentmodel",
            name="first_name",
            field=models.CharField(default="jhgdj", max_length=30),
        ),
        migrations.AddField(
            model_name="studentmodel",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                default="M",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="studentmodel",
            name="last_name",
            field=models.CharField(default="hjdgsyjd", max_length=30),
        ),
        migrations.AddField(
            model_name="studentmodel",
            name="middle_name",
            field=models.CharField(
                blank=True, default="hjdgsc", max_length=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="studentmodel",
            name="mobile_number",
            field=models.BigIntegerField(default="654164946"),
        ),
        migrations.AddField(
            model_name="studentmodel",
            name="roll_number",
            field=models.IntegerField(default="541646"),
        ),
    ]
