# Generated by Django 5.1.1 on 2024-10-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myform", "0005_alter_studentmodel_dob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentmodel",
            name="address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="studentmodel",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="studentmodel",
            name="father_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="studentmodel",
            name="first_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="studentmodel",
            name="last_name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="studentmodel",
            name="mobile_number",
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name="studentmodel",
            name="roll_number",
            field=models.IntegerField(),
        ),
    ]
