# Generated by Django 5.1.1 on 2024-09-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="studentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("fname", models.CharField(max_length=30)),
                ("roll", models.IntegerField()),
                ("address", models.CharField(max_length=100)),
                ("school_name", models.CharField(max_length=100)),
            ],
        ),
    ]
